language: bash

addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

os:
  - windows
  - linux

env:
  matrix:
    - SUITE=server-runas-splunk
    - SUITE=client-inputs-outputs
    - SUITE=upgrade-server
    - PLATFORM=windows

before_script:
  - if [ "TRAVIS_OS_NAME" = "windows"]; then choco install chef-workstation; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER ); fi
  - eval "$(chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${SUITE}-${PLATFORM}

matrix:
  include:
    - before_script:
      - chef --version
      - cookstyle --version
      - foodcritic --version
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
